# Generated by Django 5.2.4 on 2025-07-25 15:54

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration', models.CharField(db_index=True, max_length=10, unique=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('complex', models.BooleanField(default=False)),
                ('high_performance', models.BooleanField(default=False)),
                ('tailwheel', models.BooleanField(default=False)),
                ('aerobatic', models.BooleanField(default=False)),
                ('pressurized', models.BooleanField(default=False)),
                ('source_modified_timestamp', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icao_code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_time', models.DurationField(default=datetime.timedelta)),
                ('sic_time', models.DurationField(default=datetime.timedelta)),
                ('pic_time', models.DurationField(default=datetime.timedelta)),
                ('night_time', models.DurationField(default=datetime.timedelta)),
                ('solo_time', models.DurationField(default=datetime.timedelta)),
                ('cross_country_time', models.DurationField(default=datetime.timedelta)),
                ('remarks', models.TextField(blank=True)),
                ('source_modified_timestamp', models.PositiveIntegerField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='pilotlog.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='pilotlog.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='pilotlog.airport')),
                ('pilot_in_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_pic', to='pilotlog.person')),
                ('second_in_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_sic', to='pilotlog.person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
